<a href="https://colab.research.google.com/github/physicalex/python-lr/blob/master/Python_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Notebook Week 1

#Welcome to your first Python exercises. Python is a programming language widely used in science and offers powerful tools while following a simple structure.


### Let us start with some basic math operations (+,-,*,/). Simply go through the following lines by pressing shift+enter.

In [ ]:
1+7

8

In [ ]:
8+4

12

In [ ]:
2*5

10

In [ ]:
8/4

2.0

In [ ]:
2.0*5.0

10.0

#As you can see from the above examples, there are different types of numbers: integers and floats (will add a more detailed description in German). Division in Python3 automatically yields a float as the results does not necessarily have to be an integer. If you do math operations on at least one float, the result will also be a float (as indicated by .0)

###It is also possible to define variables:

In [ ]:
a = 10.0
b = 2.0

####The variable names have some restrictions. For example, they cannot have -, +, * or / in them. They can also not have a space in them. Typical naming of longer variables is done with _ or big letters:

In [ ]:
new_variable = 6
newVariable = 4

###Now we have four variables defined (a, b, new_variable, newVariable). We can do math with them just as before:

In [ ]:
new_variable + newVariable #Side note: The result is an integer, as we added integers only

10

In [ ]:
new_variable/newVariable #The result of a division is a float, even when both numbers are integers.

1.5

In [ ]:
new_variable-a #In this and the following case, at least one number is a float, such that the result will also be a float.

-4.0

In [ ]:
newVariable*b

8.0

###Variable values do not need to be numbers. There are many variable types, including "string". Strings are basically text and indicated by "":

In [ ]:
new_string = "Hello World!"

###We can use the print() function to show ("print") the value of a variable or string we enclose in parenthesis. Example print("string").

In [ ]:
print(newVariable)

4


In [ ]:
print("Hello")

Hello


In [ ]:
print(new_string)

Hello World!


###Instead of a single-value variable, we can also define a variable to be a list of numbers:

In [ ]:
new_list = [1,5,-2,8,-1,3,4,6,10]

###We can read those entries by considering their correct indices. The first index (corresponding to the first entry in the list) is always 0. For example:

In [ ]:
new_list[0]

1

In [ ]:
new_list[1]

5

In [ ]:
new_list[2] #And so on....

-2

###You can also refer to just a part of the list, for example:

In [ ]:
new_list[3:6] #This gives you the part of the list from index 3 to 6. Compare it to the original list. Once again, you will see that the index 3 corresponds to the FOURTH entry (as the indices start with 0, not with 1).

[8, -1, 3]

###Lists do not need to consist of only one variable type. We can also mix this:

In [ ]:
mixed_list = ["Hello World!", 7,10]

In [ ]:
mixed_list[0]

'Hello World!'

In [ ]:
mixed_list[1]

7

In [ ]:
mixed_list[2]

10

###In Python, if you want to use additional features for specific problems, you have the option to import so-called "libraries". Libraries are packages of functions that offer additional tools to Python's standard functions. One of the most important libraries for scientific work is "numpy".
###Numpy enables more mathematical operations, plotting and much more.
###Let us import numpy and learn some basic numpy operations that come with the library:

In [ ]:
import numpy as np #The "as np" part allows us to use the abbreviation np, whenever we want to refer to a numpy operation.

###A few examples of numpy operations and variables:

In [ ]:
np.pi #This is how you can use pi in your calculations.

3.141592653589793

In [ ]:
np.cos(np.pi) #The trigonometric functions np.cos(), np.sin(), np.tan() are offered by numpy.

-1.0

###With numpy, you can make very useful "arrays" out of lists. They can easily be used to compute vector or matrix operations. Let's have a look at those arrays and compare them to normal lists:

In [ ]:
list1 = [1,4,7,-3]
array1 = np.asarray(list1) #The function np.asarray() converts a list into a numpy-array

###Look what happens in the following operations:

In [ ]:
list1 + list1 #This just enhances the list by adding new list entries.

[1, 4, 7, -3, 1, 4, 7, -3]

In [ ]:
array1 + array1 #This, however, adds the entries of both arrays element-wise.

array([ 2,  8, 14, -6])

In [ ]:
#It also works with other basic math operations:

In [ ]:
array1-array1

array([0, 0, 0, 0])

In [ ]:
array1/(2*array1)

array([0.5, 0.5, 0.5, 0.5])

In [ ]:
array1*array1

array([ 1, 16, 49,  9])

In [ ]:
array1**2 #**2 is "squaring". So it is the same as the line before

array([ 1, 16, 49,  9])

In [ ]:
#You can reshape those arrays into any shape. For example a 2x2 matrix shape:

In [ ]:
array1 = np.reshape(array1,(2,2))

###Now you need two indices (since it is a 2D matrix) for a specific value in the array:

In [ ]:
array1[0,0] #Row 0, Column 0

1

In [ ]:
array1[0,1] #Row 0, Column 1

4

In [ ]:
array1[1,0] #Row 1, Column 0

7

In [ ]:
array1[1,1] #Row 1, Column 1

-3

###Let us add another 2x2 array, this time all in one command:

In [ ]:
array2 = np.reshape(np.asarray([4,1,-2,3]),(2,2))

In [ ]:
array2

array([[ 4,  1],
       [-2,  3]])

In [ ]:
array1*array2 #As seen before, this multiplies the values of both arrays element-wise. But of course, this is not a correct matrix multiplication. For that purpose we can use the function np.matmul():

array([[  4,   4],
       [-14,  -9]])

In [ ]:
np.matmul(array1,array2) #The correct multiplication of both matrices.

array([[-4, 13],
       [34, -2]])

In [ ]:
#Finally, let us have a look at some more useful functions from the numpy library:

In [ ]:
np.mean(array1) #Computes the mean/average value of a given list or array.

2.25

In [ ]:
np.exp(2) #Computes e^2.

7.38905609893065

In [ ]:
np.transpose(array1) #Transposes a given list/array/matrix (interchanges the row and column indices). Alternatively one can use the quicker command "array1.T":

array([[ 1,  7],
       [ 4, -3]])

In [ ]:
array1.T

array([[ 1,  7],
       [ 4, -3]])